### ISSUE TITLE
Command "." not found

### ISSUE THREAD

**Issue by rol1** [filiphric/udemy-cypress-course#11]
When I try to start the code (on windows 10) i get:
npm start

> udemy-cypress-workshop@1.0.0 start
> cd todomvc && npm start

> todomvc-testing@1.0.0 start
> ./node_modules/.bin/json-server --static . data.json -m middleware.js --config json-server.json -w

Der Befehl "." ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
PS C:\Users\RolandS\udemy-cypress-course> 

This means the command "." is either wrong spelled or could not be found

**Comment by lucas-nguyen-17** [comment]
I got the same issue, don't know how to fix it.
![image](https://user-images.githubusercontent.com/44698518/117647685-7c736180-b1b7-11eb-9947-27e28841a255.png)

**Comment by filiphric** [comment]
Hey, sorry for the issue. I have recently pulled the course from Udemy, it seems that it is still available somehow. That was the reason I overlooked these issues. Can ask which command line are you using? powershell or git bash? Can you please specify which of these is causing the issue? My guess would be that powershell might be problematic, I’d alway recommend using git bash

**Comment by lucas-nguyen-17** [comment]
I tried both powershell and git bash, but no luck.
![image](https://user-images.githubusercontent.com/44698518/117771394-40480b80-b260-11eb-98e9-d97cb7880c72.png)

**Comment by filiphric** [comment]
I searched for a bit. Since I don’t have a windows machine I’m unable to fully replicate the issue. But it seems this is an issue with how paths are recognized on windows. I think the issue might be solved by rewriting the `start` script in `todomvc/package.json` file. I’m not 100% sure about this, but maybe try rewriting it to:

`"start": "./node_modules/.bin/json-server --static data.json -m middleware.js --config json-server.json -w"`  (without the dot)

or

`"start": "./node_modules/.bin/json-server --static \. data.json -m middleware.js --config json-server.json -w"` (using backslash)

hope this helps, let me know if not

**Comment by lucas-nguyen-17** [comment]
Thanks for your suggesstion. The correct one is 
`".\\node_modules\\.bin\\json-server --static \\. data.json -m middleware.js --config json-server.json -w"`
I think you need change the README a little bit to clarify.
